export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './commentEntityController.service';
import { CommentEntityControllerService } from './commentEntityController.service';
export * from './commentPropertyReferenceController.service';
import { CommentPropertyReferenceControllerService } from './commentPropertyReferenceController.service';
export * from './profileController.service';
import { ProfileControllerService } from './profileController.service';
export * from './root.service';
import { RootService } from './root.service';
export * from './userEntityController.service';
import { UserEntityControllerService } from './userEntityController.service';
export * from './userPropertyReferenceController.service';
import { UserPropertyReferenceControllerService } from './userPropertyReferenceController.service';
export * from './userSearchController.service';
import { UserSearchControllerService } from './userSearchController.service';
export * from './videoEntityController.service';
import { VideoEntityControllerService } from './videoEntityController.service';
export * from './videoPropertyReferenceController.service';
import { VideoPropertyReferenceControllerService } from './videoPropertyReferenceController.service';
export const APIS = [AuthControllerService, CommentEntityControllerService, CommentPropertyReferenceControllerService, ProfileControllerService, RootService, UserEntityControllerService, UserPropertyReferenceControllerService, UserSearchControllerService, VideoEntityControllerService, VideoPropertyReferenceControllerService];
