/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Channel } from './channel';
import { GrantedAuthority } from './grantedAuthority';
import { Link } from './link';


export interface EntityModelUser { 
    email?: string;
    channel?: Channel;
    enabled?: boolean;
    authorities?: Array<GrantedAuthority>;
    credentialsNonExpired?: boolean;
    accountNonExpired?: boolean;
    accountNonLocked?: boolean;
    _links?: { [key: string]: Link; };
}

